# Generated by Django 5.1.13 on 2026-03-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0008_professional_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('topic', models.CharField(max_length=300)),
                ('content', models.TextField(help_text='AI-generated tutorial content (markdown)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_tutorials', to='semesters.subject')),
            ],
            options={
                'verbose_name': 'Unit Tutorial',
                'verbose_name_plural': 'Unit Tutorials',
                'ordering': ['subject', 'unit_number', 'topic'],
                'unique_together': {('subject', 'unit_number', 'topic')},
            },
        ),
    ]
